//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parketin
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEICULO
    {
        public int ID { get; set; }
        public string NOME_VEICULO { get; set; }
        public string PLACA_VEICULO { get; set; }
        public string COR_VEICULO { get; set; }
        public string TIPO_VEICULO { get; set; }
        public string FABRICANTE { get; set; }
        public string MODELO_VEICULO { get; set; }
    }
}
